stages:
    - deploy
    - refresh

variables:
    BUCKET_NAME: "zixun-hubstudio-portal-ap-southeast-1"
    SOURCE_FOLDER: "dist"

deploy-website:
    stage: deploy
    only:
        - dev
        - master
    tags:
        - build-aws
    script:
        - yarn
        - npm run build
        - AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY aws s3 cp $SOURCE_FOLDER s3://$BUCKET_NAME --recursive
        #- aws cloudfront create-invalidation --distribution-id ENRYYMH1EWQLE --paths "/*"
    when: manual
